### ISSUE TITLE
[Critical] Keyboard Bug!

### ISSUE THREAD

**Issue by RealPlurr** [irv77/eaglercraft-mobile#1]
On chrome android there is critical bug with keyboard, you can't set name beacuse when you type it just wont type in text area but when you press <- aka delete it deletes default username also some special characters can be placed somehow. Joining public server with any authorization plugin is impossible beacuse you can't really type you press chat icon and then keyboard and keyboard wont pop up and when it pop up it again wont type.

By the way still thanks author it added ability for single player worlds or where is no normal name or chat needed but still I will be happy with a lot of other people if keyboard bug will be fixed;3

**Comment by RealPlurr** [comment]
Additional notes about device: Redmi 8. Browser: Chrome (latest version from play market not beta)

**Comment by FlamedDogo99** [comment]
When @irv77 updates his script to [Eagler Mobile v3.0.4](https://raw.githubusercontent.com/FlamedDogo99/EaglerMobile/v3.0.4/eaglermobile.user.js), this issue should be resolved.
